---

- name: Updated pipeline-library with correct git branch
  replace:
    path: "{{ inventory_dir }}/../test/create-pipeline-library.groovy"
    regexp: "https://github.com/redhat-cop/pipeline-library.git"
    replace: "{{ repository_url }}"

- name: Updated Jenkinsfile tests with correct git branch
  replace:
    path: "{{ item }}"
    regexp: "pipeline-library@master"
    replace: "pipeline-library@{{ repo_ref }}"
  with_fileglob: "{{ inventory_dir }}/../test/Jenkinsfile*"

- name: Load Jenkinsfile content into memory
  set_fact:
    jenkins_test_files: "{{ jenkins_test_files|default([]) + [{'path': item, 'content': lookup('file', '{{ item }}') }] }}"
  with_items: "{{ lookup('fileglob', '{{ inventory_dir }}/../test/Jenkinsfile-*', wantlist=true) }}"
